name: Build and Test

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore WalrusEtl.sln
      - name: Build
        run: dotnet build --no-restore WalrusEtl.sln
      - name: Test
        run: dotnet test --no-build WalrusEtl.sln
